### ISSUE TITLE
תאריך פטירה עברי קופץ בכרטיס נפטר

### ISSUE THREAD

**Issue by osnatf** [taviram/OliveMt#13]
חידדתי את התיקון

**Comment by taviram** [comment]
הבנתי מתקנת

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
אני רואה שדווקא תאריך הפטירה הלועזי קופץ שמאלה ולא מיושר לשורה שמעליו

**Comment by taviram** [comment]
@oritdi באיזה מסך את מסתכלת?

**Comment by oritdi** [comment]
במסך של 1280*800 
![image](https://cloud.githubusercontent.com/assets/23609951/20588874/387c6c78-b221-11e6-81b8-2685b0203b68.png)

**Comment by oritdi** [comment]
במסך גדול זה בסדר אבל אז יש בעיה אחרת - שהכפתור והלינק עולים על הטקסט של הכרטיס
![image](https://cloud.githubusercontent.com/assets/23609951/20588907/65c6bbac-b221-11e6-8228-0f0f7330316a.png)

אפתח לזה הערה נפרדת

**Comment by taviram** [comment]
תוקן

**Comment by taviram** [comment]
@oritdi את יכולה לבדוק

**Comment by oritdi** [comment]
התאריכים מיושרים בסדר.
יש בעיות עדיין עם החלק התחתון של החלון, אגיב בהערה ההיא.
(את זאת אפשר לסגור)
