### ISSUE TITLE
מרכוז טקסט ומשולשים בתפריטים

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#15]
- עדיין לא תוקן
הטקסטים בתפריטים  #והמשולשים לא ממורכזים
![image](https://cloud.githubusercontent.com/assets/23609951/20474668/538f4fe2-afd0-11e6-8308-d3caeafeb563.png)
![image](https://cloud.githubusercontent.com/assets/23609951/20474681/6070b82c-afd0-11e6-92d4-1cdd1decb1e1.png)

**Comment by taviram** [comment]
@oritdi במסך של הנייד זה נראה לי ממורכז בבוקר אבדוק במסך גדול

**Comment by oritdi** [comment]
עדיין מסמכים ושירותים לא ממורכז. אמנם זה לא פעיל אבל נראה מוזר
גם גובה השורה של כל הטקסם בתפריט קצת גבוה מדי - לא במרכז
![image](https://cloud.githubusercontent.com/assets/23609951/21080057/c1e4818c-bfad-11e6-94c0-fc8461ed018a.png)

**Comment by taviram** [comment]
הוספתי תיקונים 
@oritdi תבדקי

**Comment by oritdi** [comment]
מצויין, סוגרת # @taviram
