### ISSUE TITLE
מספרים בסוגריים

### ISSUE THREAD

**Issue by yaniv73** [taviram/OliveMt#17]
בדרופדאון חיפוש יש בעיית פירמוט של המספרים בסוגריים
אם זה לא ניתן לפתרון מבחינתך אנא עדכני ואשקול פיתרון מבחינתי
![default](https://cloud.githubusercontent.com/assets/23522422/20968999/a35a8eb2-bc8f-11e6-97df-fdf25a499772.jpg)

**Comment by taviram** [comment]
@yaniv73 העלאתי תיקון תבדוק

**Comment by yaniv73** [comment]
מאושר
