### ISSUE TITLE
אייקון מרכוז מפה

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#20]
צריך להיות במרכז הריבוע שלו.
כרגע הוא גם צמוד לשוליים. צריך להיות בדיוק מתחת לאייקונים של הזום של גוגל

![image](https://cloud.githubusercontent.com/assets/23609951/21227471/d1ecd402-c2e2-11e6-92c4-c8ad8ac49952.png)

עשיתי קובץ חדש (אעלה אותו לדרייב לתיקיית אייקונים), עם ריבוע גדול יותר ועם פינות מעוגלות, באותו גודל של האייקונים של גוגל ועליו האייקון של המרכוז (הכהיתי אותו קצת שיראה יותר דומה לאייקונים של גוגל)
התאמתי גם את גודל האייקון כדי שיצא בדיוק במרכז.
אם את בכל זאת יוצרת את ריבוע הרקע בקוד אז תעשי פינות ברדיוס 2 פיקסלים.

כמו כן לא הייתי עושה לו צל כל כך גדול. תסתכלי איך זה על רקע מפה, הוא בולט משמעותית ליד האייקונים האחרים
צריך להיות צל ממש מינורי. של פיקסל אחד אפילו
@taviram

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
סוגרת
