### ISSUE TITLE
מרכוז והגדלת החיצים בתפריט

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#26]
שיהיה כמו בעברית - החץ צריך להיות גדול יותר
וחייב להיות ממורכז למלבן
![image](https://cloud.githubusercontent.com/assets/23609951/22324029/421cabca-e3af-11e6-84cb-9c10262d00f6.png)

**Comment by taviram** [comment]
תוקן . לבדיקתך @oritdi

**Comment by oritdi** [comment]
סבבה, סוגרת @taviram
