### ISSUE TITLE
תפריט ראשי - גודל ופיזור רווחים

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#28]
להגדיל את הטקסט לגודל 15 פיקסלים ולפזר כך שהרווחים יהיו שווים
![image](https://cloud.githubusercontent.com/assets/23609951/22335385/343f34c2-e3e7-11e6-8438-e1f585b5b300.png)

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
בסדר, סוגרת
