### ISSUE TITLE
יישור כפתור החיפוש

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#32]
צריך לישר את הכפתור ואת המילה האחרונה בתפריט לתיבת החיפוש
![image](https://cloud.githubusercontent.com/assets/23609951/22403579/ba6962a4-e624-11e6-924f-49b3227c6a5e.png)

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
מצויין, סוגרת
