### ISSUE TITLE
אייקון מרכוז מפה

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#33]
שיניתי את האייקון - צריך להיות באותו גודל של הכפתורים של גוגל 
(אותה הערה מופיעה גם בעברית)
יש קובץ מעודכן בדרייב
https://drive.google.com/file/d/0B0PuzbYpzagCRW9GY0Jsd0VzeWM/view?usp=sharing

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
סבבה, סוגרת
