### ISSUE TITLE
מסגרת כחולה בטפסים או בכפתורים

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#38]
מופיעה מסגרת כחולה כשנמצאים בתוך שדה טופס (חיפוש מתקדם, מצב עריכה וכו')
וגם בכפתורים שכבר הוקלקו פעם אחת.
בטפסים יש צורך בכזה חיווי אבל הכחול הדיפולטי לא שייך.
עדיף שתהיה מסגרת בצבע הטקסט של אותו טופס.
בכפתורים זה לא נצרך לדעתי כי הם משנים צבע גם ככה
 @yaniv73 @taviram 
![image](https://cloud.githubusercontent.com/assets/23609951/22420277/61d1627e-e6ea-11e6-9ffe-be48627f3433.png)

![image](https://cloud.githubusercontent.com/assets/23609951/22420324/9c0bd8e8-e6ea-11e6-9895-aed0cdf28c19.png)

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
סבבה, סוגרת
