### ISSUE TITLE
אייקון 'הינך נמצא במצב עריכה' - מתחלף בין העברית לאנגלית

### ISSUE THREAD

**Issue by oritdi** [taviram/OliveMt#39]
![image](https://cloud.githubusercontent.com/assets/23609951/22420435/0963bd66-e6eb-11e6-9def-db12032d9aa7.png)

![image](https://cloud.githubusercontent.com/assets/23609951/22420449/165333bc-e6eb-11e6-9104-2e1a4d5b2196.png)

**Comment by taviram** [comment]
תוקן

**Comment by oritdi** [comment]
סוגרת
