### ISSUE TITLE
במצב עריכה לשנות את הצבע של התפריט בכרטיס נפטר

### ISSUE THREAD

**Issue by taviram** [taviram/OliveMt#7]
במצב hover ובמצב acctive 

![image](https://cloud.githubusercontent.com/assets/2620317/20384479/abc6b05e-acbc-11e6-8fd8-d042fcbef122.png)

לא בטוח יעלה לפני יום ראשון

**Comment by oritdi** [comment]
עדיין אפור

**Comment by taviram** [comment]
בוצע

**Comment by oritdi** [comment]
מעולה, סוגרת
