### ISSUE TITLE
תאריך פטירה עברי - קופץ

### ISSUE THREAD

**Issue by osnatf** [taviram/OliveMt#8]

**Comment by taviram** [comment]
לא ברור לי מה הכוונה כי אצלי זה נראה טוב.
באיזה מסך את מסתכלת?

![image](https://cloud.githubusercontent.com/assets/2620317/20386092/b8a0dee8-acc2-11e6-8bfe-b1322d266d4e.png)

**Comment by osnatf** [comment]
בכרטיס נפטר
